# Generated by rstantools.  Do not edit by hand.

# names of stan models
stanmodels <- c("horseshoe_MA", "horseshoe_MA_ml", "horseshoe_MA_ml_noint", "horseshoe_MA_noint", "hs_prior", "lasso_MA", "lasso_MA_ml", "lasso_MA_ml_noint", "lasso_MA_noint", "lasso_prior", "prior_meff")

# load each stan module
Rcpp::loadModule("stan_fit4horseshoe_MA_mod", what = TRUE)
Rcpp::loadModule("stan_fit4horseshoe_MA_ml_mod", what = TRUE)
Rcpp::loadModule("stan_fit4horseshoe_MA_ml_noint_mod", what = TRUE)
Rcpp::loadModule("stan_fit4horseshoe_MA_noint_mod", what = TRUE)
Rcpp::loadModule("stan_fit4hs_prior_mod", what = TRUE)
Rcpp::loadModule("stan_fit4lasso_MA_mod", what = TRUE)
Rcpp::loadModule("stan_fit4lasso_MA_ml_mod", what = TRUE)
Rcpp::loadModule("stan_fit4lasso_MA_ml_noint_mod", what = TRUE)
Rcpp::loadModule("stan_fit4lasso_MA_noint_mod", what = TRUE)
Rcpp::loadModule("stan_fit4lasso_prior_mod", what = TRUE)
Rcpp::loadModule("stan_fit4prior_meff_mod", what = TRUE)

# instantiate each stanmodel object
stanmodels <- sapply(stanmodels, function(model_name) {
  # create C++ code for stan model
  stan_file <- if(dir.exists("stan")) "stan" else file.path("inst", "stan")
  stan_file <- file.path(stan_file, paste0(model_name, ".stan"))
  stanfit <- rstan::stanc_builder(stan_file,
                                  allow_undefined = TRUE,
                                  obfuscate_model_name = FALSE)
  stanfit$model_cpp <- list(model_cppname = stanfit$model_name,
                            model_cppcode = stanfit$cppcode)
  # create stanmodel object
  methods::new(Class = "stanmodel",
               model_name = stanfit$model_name,
               model_code = stanfit$model_code,
               model_cpp = stanfit$model_cpp,
               mk_cppmodule = function(x) get(paste0("rstantools_model_", model_name)))
})
